# Generated by Django 2.2.12 on 2020-04-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200420_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='HGgfh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhnn', models.BigIntegerField()),
            ],
        ),
    ]
